### ISSUE TITLE
Don't display field information

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rcse#10]
RCSE v1
I reach id_74 and it doesn't want to go further in the right window.

after reinitiate id It even created duplcated id.

I attached the work in progress before trouble.

[test2.zip](https://github.com/Rolisteam/rcse/files/2761046/test2.zip)

**Comment by obiwankennedy** [comment]
Some id were missing, RCSE counts how many field you have while reloading rcs file .
Your file has 67 fields, so next Id is 68. I remove all holes in id numbers and it fixed this issues.

[test_fixed2.zip](https://github.com/Rolisteam/rcse/files/2761779/test_fixed2.zip)

**Comment by sioc-de-narf** [comment]
I'll check that tonight :)

**Comment by sioc-de-narf** [comment]
ok
