### ISSUE TITLE
Feature request : equidistance distribution

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rcse#13]
Could we have an equidistance distribution between the two end of a selection for all selected elements (position based on their centers) ?

**Comment by obiwankennedy** [comment]
I need more details about that. 
I already implements several features to help placing object.
Do you want something to make this: 
![ticket13_rcse](https://user-images.githubusercontent.com/69177/51241475-2fcc4280-197e-11e9-8d82-622eba4d1e77.png)

**Comment by sioc-de-narf** [comment]
Exactly and the same verticaly.
And use the Center of the object to do the math.

**Comment by sioc-de-narf** [comment]
Of course not just with 3 objects but with nth :)
