### ISSUE TITLE
Feature request : Display text

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rcse#14]
Could we have a type of text that can not be edited so we can write on the sheet without the need of all being image based ?

**Comment by obiwankennedy** [comment]
Sure, QML provides several kind of item to do so. Label and Text. 
I know that some users have made charactersheet with qml code only, but they use other editor to train themselves and write down the qml code.

Obviously, the resulting character sheet was very light and easy to use.
__
Currently, To do a Text field in rcse, you can use a TextInput and set it as read only.
