### ISSUE TITLE
Feature request : Display only field

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rcse#15]
Could we have a kind of field that display the value of an other field and cannot be edited ?

I am sure that can be done through the QML, but editing QML is just hell currently (see Feature Request : customize the QML code edit).

**Comment by obiwankennedy** [comment]
To prevent the edition you can make the field in readonly mode.
And to display the value of another field it is easy using QML or formula.

By formula: (in this example, we want to show the intelligence (id_34) score in id_60 field).
* Edit the value of the field 
* set =${id_34} or =${intelligence}


in QML:

```
TextInput {
id: id_60
[...]
text: id_34.text
[...]
}
```

**Comment by obiwankennedy** [comment]
Does I answer your question or do you need more info or dev ?
