### ISSUE TITLE
bug : check box unique size

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rcse#20]
whatever size is set up for a check box i end up with the same tiny check box

**Comment by obiwankennedy** [comment]
In v1.8.2, we use the first set of windows element which have some limitations. We now takes advantage of the most recent set of windows elements and they can support size change.

**Comment by sioc-de-narf** [comment]
HOw can I have access to those ?

**Comment by sioc-de-narf** [comment]
Please share latest compatible with 1.8.2

**Comment by obiwankennedy** [comment]
I don't think it is possible to use them on 1.8.2.
