### ISSUE TITLE
Bug : textinput as list : unique size 

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rcse#21]
whatever font and font size I select I end up with a list with the same font, font weight and font size.

My choices are not used.

**Comment by obiwankennedy** [comment]
what is a textinput as list ?

**Comment by sioc-de-narf** [comment]
As list of choices, with possible values 4,6,8,10,12

**Comment by sioc-de-narf** [comment]
check the screenshot

![list](https://user-images.githubusercontent.com/14063185/51603971-9f58a980-1f0b-11e9-83d8-d0b0e16b1ee7.png)

**Comment by sioc-de-narf** [comment]
no answer ?

**Comment by obiwankennedy** [comment]
It is a bug, It will fixed in rolisteam 1.9. To fix you problem on your side. It requires to amend the code of each selection field you have.

**Comment by sioc-de-narf** [comment]
could you give me the code to amend ?

**Comment by obiwankennedy** [comment]
Let me think about it.
