### ISSUE TITLE
bug : check box no value

### ISSUE THREAD

**Issue by sioc-de-narf** [Rolisteam/rcse#23]
If you add checkbox, the field value isn't initialized and don't change by being check or unchecked.

**Comment by sioc-de-narf** [comment]
in the same way forcing it to 1 or 0 doesn't check or uncheck

**Comment by obiwankennedy** [comment]
yes, checkbox are buggy.

I have a script that correct automatically all checkboxes at once.

Bad Checkboxes:
```
CheckBoxField {//canotage_acquit
    id: _id_154
    text: id_154.value
    textColor:"#ff000000"
    x:420*parent.realscale
    y:140*parent.realscale
    width:40*parent.realscale
    height:25*parent.realscale
    color: "#00000000"
    visible: root.page == 1? true : false
    readOnly: id_154.readOnly
    onTextChanged: {
    id_154.value = text
    }
}
```

Good Checkbox:
```
CheckBox {//canotage_acquit
    id: _id_154
    checked: id_154.value=== "1" ? true : false
    x:420*parent.realscale
    y:140*parent.realscale
    width:40*parent.realscale
    height:25*parent.realscale
    visible: root.page == 1? true : false
    enabled: !id_154.readOnly
    onClicked: {
    if(checked)
        id_154.value = "1"
    else
        id_154.value = "0"
    checked = Qt.binding(function() { return id_154.value === "1" ? true : false })
    }
}
```

**Comment by sioc-de-narf** [comment]
Are you sure the object name is to be changed from CheckBoxField to CheckBox ?

Because if i change it i got the error CheckBox is not a type and then i got the error Cannot assign to non-existent property "onClicked"

So looks like that Good CheckBox is not compatible with 1.8.2

**Comment by obiwankennedy** [comment]
No it missing import.
You have to add at the beginning of the file:
`import QtQuick.Controls 1.3`

**Comment by sioc-de-narf** [comment]
My first 3 lines are now :
import QtQuick 2.4
import "qrc:/resources/qml/"
import QtQuick.Controls 1.3

and i still got the error : Cannot assign to non-existent property "onClicked"

**Comment by obiwankennedy** [comment]
may be 1.4 instead 
or change the onClicked by onCheckedChange. but i recommend to protect the code: 

```
if(checked && id_154.value == "0")
        id_154.value = "1"
    else if(id_154.value == "1")
        id_154.value = "0"
```
The Qt documentation tells that it should exist: 
5.6:
http://doc.qt.io/qt-5.6/qml-qtquick-controls-checkbox.html
5.9:
http://doc.qt.io/qt-5.9/qml-qtquick-controls-checkbox.html

as clicked exists the way to be triggered is onClicked
