### ISSUE TITLE
Problem Multiple pages in RCSE

### ISSUE THREAD

**Issue by osfrance** [Rolisteam/rcse#24]
<p align='center'><img src="https://raw.githubusercontent.com/Rolisteam/rolisteam/master/resources/logo/1000-rolisteam.png"/></p>

#Your configuration:
Rolisteam version: 1.9.1
Operating System and version (remove irrelevant): 
*  Linux (Ubuntu 19.10)

Rolisteam Setting (remove irrelevant):  
* GM and Server

#What did you do ? (Explain each step from starting rolisteam to the issue)
- 
-
-

#What did you expect to see ? (Make sentences and explains in details with words)
- Launch RCSE
- Set Image Background for page 1
- Add Page 2
- Set Image Background for page 2
- Generate code

#What did you get instead ? (Describe in details the issue) 
- I don't see image background in page 2
- I don"t see difference from generated code when I add page 2 background

**Comment by obiwankennedy** [comment]
Do the background images have the same size/resolution ? Exactly the same size/resolution ?

**Comment by osfrance** [comment]
Oh yeah it's work ! the third picture had 1 pixel line more ... Thanks for help !
What's the best size for an character sheet picture ? (I use 2480x3360, it's not too big ?)
