### ISSUE TITLE
Help With Dicebuttons, buttons and Formulas

### ISSUE THREAD

**Issue by osfrance** [Rolisteam/rcse#25]
Hi, 
I want to make some Dicebuttons in charactersheet to test attributes like this : 
If 1d100 result if bigger than player attribute CC, wrote RATE (die), else wrote REUSSI (die)

If I try this roll in chat : !1d100i[>${CC}]{"RATE (%1)"}{"REUSSI (%1)"} it's work
But if I try to put this formula to a Dicebutton roll it's don"t work... (with or without char "!")

And my second question is : What's the difference between DiceButton and Button and how to use Button ?

Thanks !

**Comment by obiwankennedy** [comment]
1/ The button is to call any functions, so you have to wrote those functions and call them with the button.

2/ It is without !
the dice command is not a formula (no =) it is the value of the field.
How did you try ? on RCSE or in rolisteam ?

**Comment by osfrance** [comment]
Thanks for help !
I try in Rolisteam.
You can view my test : [test-Des.rcs.zip](https://github.com/Rolisteam/rcse/files/4409428/test-Des.rcs.zip)

**Comment by obiwankennedy** [comment]
Is it hurry ? Can you wait to the week-end ?

**Comment by osfrance** [comment]
Sure ! I think you have many bugs to repair and codes to make, it's not urgent ...

**Comment by osfrance** [comment]
If it's can help you, I have the same problem if I put 1d100i[>${CC}]{"RATE (%1)"}{"REUSSI (%1)"} in dice bookmark... the problem is ${CC} the dicebutton or dice bookmark can't access to this variable (I'm in NPC chat and not player chat).
You can test the command !${CC} in chat [work], and ${CC} in dicebutton or dice bookmark [not work])

**Comment by obiwankennedy** [comment]
Ok I download the page I will check out that.

**Comment by obiwankennedy** [comment]
When the GM is click on the button it does not work but if the playing click on it, it works !!

See screenshot below. The gm is you and the character is Lynn Gray-Rike. 

![Screenshot from 2020-04-05 01-43-37](https://user-images.githubusercontent.com/69177/78463600-fd237c80-76de-11ea-8b7a-472f7b1feb1e.png)

I let you close this ticket. :nerd_face:

**Comment by osfrance** [comment]
Oh great ! thanks you it's work !
Have you an example how to use "button" (in doc: Add clickable button to call qml function or make any computation) ?
