### ISSUE TITLE
RCSE 1.9.3 AppImage - L'affichage ne fonctionne pas

### ISSUE THREAD

**Issue by jc-fgt** [Rolisteam/rcse#26]
Bonjour, 

Lorsque j'ai parlé d'un problème de lancement sur RCSE 1.9.3  dans une autre issue, J'ai voulu tester via la version AppImage 1.9.3. 

J'ai eu un autre souci : 
L'application se lance bien, je peux créer ma fiche, mais lorsque je veux visualiser dans la partie Affichage
![Capture d'écran Deepin_zone de sélection _20201127105735](https://user-images.githubusercontent.com/75116332/100436248-622d4780-309f-11eb-9263-4de4c43871f9.png)
Le bouton de génération de code fonctionne mais je n'ai aucun affichage

J'ai testé avec la version 1.9.2, ça se passe bien.

J'ai vu les erreurs en dessous mais étant donné que la 1.9.2 AppImage a l'air de passer, je doute que ce soit lié. Si ?

**Comment by jc-fgt** [comment]
oui

**Comment by jc-fgt** [comment]
ça se passerait mieux en le retirant ?

**Comment by obiwankennedy** [comment]
il faut essayer oui.

**Comment by jc-fgt** [comment]
J'ai tenté, ça ne change rien et quand je génère le code, il ajoute la ligne incriminée

**Comment by obiwankennedy** [comment]
C'est control et layout qui sont pas bon, je viens de checker. Il manque une dependences au deb, il suffit d'installer:
`sudo apt install qml-module-qtquick-layouts qml-module-qtquick-controls2`

**Comment by obiwankennedy** [comment]
après ça, rcse devrait fonctionnait normalement.

**Comment by jc-fgt** [comment]
Pour les dépendances au deb, je les ai
![image](https://user-images.githubusercontent.com/75116332/100584455-731ec880-32ec-11eb-8ca7-00c14cdba602.png)

Mais ça ne change pas grand chose

En passant, j'ai vu qu'il y a deux AppImages de la même version
![image](https://user-images.githubusercontent.com/75116332/100584736-c5f88000-32ec-11eb-8309-71e2f37d535f.png)

**Comment by jc-fgt** [comment]
J'ai remarqué que quelque soit l'image que je lui mets en fond d'écran (petite taille, grande taille, jpg, png) j'ai l'erreur qui suit

![image](https://user-images.githubusercontent.com/75116332/100586054-dad61300-32ee-11eb-9b7a-2fe787c0e02f.png)

Et je viens de voir quelque chose, apparemment le AppImage n'a pas certains modules en interne, du moins c'est l'impression que j'en ai.
![image](https://user-images.githubusercontent.com/75116332/100586342-4d46f300-32ef-11eb-97e5-47a028e42a2b.png)

**Comment by obiwankennedy** [comment]
Bonjour, 
Le setImage n'est pas une erreur, c'est un log d'information mais il est taggé en erreur, c'est ça le problème.

Après, il semble bien que des modules QtQuick ne soit pas trouvable. Le processus de création du appimage devrait mettre ces modules dedans. C'est étrange qu'ils n'y soient pas.

**Comment by obiwankennedy** [comment]
J'ai refait un appimage, il fonctionne sur ma machine.

https://sourceforge.net/projects/rolisteam/files/1.9.3/RCSE-1.9.3-x86_64.AppImage/download

**Comment by jc-fgt** [comment]
Top c'est fonctionnel :)
