### ISSUE TITLE
Create a 2 page Character sheet -> Background Image invisible

### ISSUE THREAD

**Issue by HarvoireSamuel** [Rolisteam/rcse#3]
At the creation of a new character sheet : I try to create 2 pages, with one field in each of them

![rcse1](https://cloud.githubusercontent.com/assets/9363228/23323055/1fbe1bf0-fae7-11e6-9a29-be55f0700c4d.JPG)
![rcse2](https://cloud.githubusercontent.com/assets/9363228/23323059/21190a00-fae7-11e6-86f4-eb6ae2dc8c90.JPG)

And then, when i click on "Generate" i have this : 

![rcse3](https://cloud.githubusercontent.com/assets/9363228/23323073/2ea48f46-fae7-11e6-8ebd-e5334c0044f8.JPG)
![rcse4](https://cloud.githubusercontent.com/assets/9363228/23323076/303ab9a2-fae7-11e6-8eab-02add4d9de26.JPG)

**Comment by obiwankennedy** [comment]
Could you give me the resolution of both images ?

**Comment by obiwankennedy** [comment]
The resolution has to be exactly the same.

**Comment by HarvoireSamuel** [comment]
... Okay, my bad on that one, the resolution of the second image were smaller on the length by ONE pixel.  Sorry about that. 
But it would be nice to have this information somewhere, maybe it's on the wiki (And if it's the case, blame me XD) but on the videos you made and inside the application, there is no indication of this rule. Ok, it's obvious and even I did it without thinking, but still. ^^

But anyway, thanks !

**Comment by obiwankennedy** [comment]
Sure,  i plan to inform user that the second background must have the same resolution. And i will check the documentation.
