### ISSUE TITLE
Field names won't update on characters

### ISSUE THREAD

**Issue by Alkor1** [Rolisteam/rcse#4]
**Description :** 
I tried to edit a character sheet after adding values to a character. When I tried to use the **name** of the field (not the ID) in a formula, it didn't work. I checked the code of the page with a text editor to see what was the issue, and noticed the name of the fields edited after the character was created kept its old name or was blank if the field was added after.

**Issue :** 
The field names won't update on already created characters.

**Steps to reproduce :** 
Create a character sheet 
Add a few fields with names
Optional : create formulas using the field names
Add a character
Change the name of a few fields
Try to make a formula with the **new** names **(won't work**)
Try to make a formula with the **old** names (**should work**)

**Comment by obiwankennedy** [comment]
this commit  must fixes the issue. 

https://github.com/Rolisteam/RCharacterSheet/compare/5710b846159d3425018c70b0b3f9e6785f98e6d4...99bca3717b944f35478262b607f34e919d83baf5#diff-84dd5e792e2f73cd4d45a8fa95fbc79b

**Comment by obiwankennedy** [comment]
Please try rcse v1.0.3, you can download it from http://www.rolisteam.org/download.html 

If you are on windows, you just have to download and reinstall rolisteam.

Then, let me know if it fixes the issue.
