### ISSUE TITLE
Multiple page Character Sheet Fields improperly placed. 

### ISSUE THREAD

**Issue by develroo** [Rolisteam/rcse#5]
Basically when creating a multipage character sheet, fields placed on the second page and verified with View, show up in Rolisteam as being embedded onto the first page.

This is the view [in rcse](https://i.imgur.com/xl2c3c6.png) and via the [View tab](https://i.imgur.com/8Lin1OA.png)

However when you open it in Rolisteam the 2nd page elements are [embedded into the 1st page](https://i.imgur.com/r1HQyxJ.png) and the 2nd page shows [no fields at all](https://i.imgur.com/f8M9eLo.png)

I've also noticed looking at the save file there [is a page element]( https://pastebin.com/45p5KtZP) but it seems it is always set to 0. Not sure if that is correct or not?

**Comment by obiwankennedy** [comment]
This bug is known and already fixed, the work around is to change the file by your own way to put 1 on all fields belonging to the second page.

You can also try to compile RCSE from the git repo.

**Comment by develroo** [comment]
Hmm. So just by changing page 0 to page 1 should fix the problem? Ok will try that.

**Comment by develroo** [comment]
Hmmm. Changed the fields in the save file. But seemed not to do anything. It was like it just ignored the page value entirely.

**Comment by obiwankennedy** [comment]
Could you send me the file ? I will check. By the way, I will release a new version of RCSE. To fix all this kind of issue.

**Comment by develroo** [comment]
You can download it from [here](https://dropfile.to/tdVnnvK) for the next 23 hours to test if you like. 

I'll wait for the new release :)

**Comment by obiwankennedy** [comment]
I just release the rcse v1.0.3. 
Please download it and let me know if it change something.

If your are windows you must download rolisteam setup. It will install rolisteam and the new version of RCSE. 
Other platform has a dedicated package for RCSE.

**Comment by develroo** [comment]
Whoop. Yeah. Seems to have fixed that particular sheet. But am I wrong in thinking there are new features in rcse ? I noticed a fx() function button for the first time and when I right click on the page I now have more optons I think. Also another tab for stored images.

So yeah.. great work. Will now see if I can finish that sheet. 

Thanks!

**Comment by obiwankennedy** [comment]
1/ That right. There is some new features. The new tab offers a view on the stored images. If something is wrong or if you want to change the background image you can do it thank to this tab.
It is also useful if you want charactersheet to stored avatar of characters. You put images into the character sheet images data. You set a proper Id. Then, you can copy/paste the path as value of image field for your characters.

2/ the fx button allows you to call any function you wrote.

3/ In the menu, you can set properties. In these properties you can set how the qml code is generated.
If you want the qml to adapt it self to the character sheet window or if you want it to have fixed size.
You can also put some code here and select where you should put it. 
So, you can add function and add a button to call this new function.

4/ The selection on the editor is now visible (red border). You can select several items on the editor and apply some actions to each selected items.
